.TH WORDWARVI "6" "May 2007" "wordwarvi" "Games"
.SH NAME
wordwarvi \- Old school '80's style side scrolling space shoot'em up game.
.SH SYNOPSIS
.B wordwarvi
.SH DESCRIPTION
.\" Add any additional description here
.PP
wordwarvi, or "Word War vi", is an old school '80's style side 
scrolling space shoot'em up video game.  It relies on Gnome for
graphics platform, and libsndfile and libportaudio for sound.
.PP You pilot your "vi-per" craft through core memory, trying to
avoid OS defenses and wipe out the memory hogging emacs processes
and rescue lost vi-per pilots stranded from crashed vi sessions
before heading through the socket to the next node in the cluster
to do it all over again.
.PPControls:
.PP 
Arrow keys control movement (or vi's hjkl keys will work too,
of course.)
.PP
Q puts in a quarter, and starts the game.
.PP
Z fires a laser
.PP
C drops chaff (to confuse heat seeking missiles).
.PP
B drops bombs.

.SH ENEMIES
.PP 
Rockets.  Avoid hitting them.
.PP 
Heat seeking SAMs.  Avoid.
.PP 
Tentacles.  Shoot lightning.  Avoid.
.PP 
Blimps (representing emacs).  Will shoot heat seeking missiles.  
Will leak LISP code.
.PP 
GDB processes.  Will attempt to ptrace you with heat seeking probes.  Avoid and/or kill.
.PP 
.SH GOOD LUCK
.SH FILES
.SH AUTHOR
Written by Stephen M. Cameron 
.br
