
%.wav:	%.ogg
	oggdec $<

all:	18382_inferno_hvylas.wav \
	18384_inferno_largex.wav \
	18385_inferno_laserbeam.wav \
	18386_inferno_lightrl.wav \
	18390_inferno_plascanh.wav \
	18395_inferno_rltx.wav \
	18399_inferno_stormplas.wav \
	34561__DrNI__ob12_triangular_growling_wailing.wav \
	9679__dobroide__firecracker.04_modified.wav \
	dtox3monomix.wav \
	ground_smack.wav \
	lucky13-steve-mono-mix.wav \
	thunder.wav \
	us_quarter.wav \
	cardoor.wav \
	ow_my_spine.wav \
	help_down_here.wav \
	woohoo.wav \
	37236_Shades_Gun_Pistol_one_shot_.wav \
	clang.wav \
	abducted.wav \
	help_up_here.wav \
	bodyslam.wav \
	fallingscreamhi.wav \
	UseTheSource.wav \
	ooooof.wav \
	terrible_pain1.wav \
	terrible_pain2.wav \
	might_be_dying.wav

clean:
	/bin/rm -f *.wav
