
%.wav:	%.ogg
	oggdec $<

all:	dtox3monomix.wav \
	lucky13-steve-mono-mix.wav \
	us_quarter.wav \
	ow_my_spine.wav \
	help_down_here.wav \
	woohoo.wav \
	clang.wav \
	abducted.wav \
	help_up_here.wav \
	bodyslam.wav \
	fallingscreamhi.wav \
	UseTheSource.wav \
	ooooof.wav \
	stonebang1.wav \
	stonebang2.wav \
	stonebang3.wav \
	stonebang4.wav \
	stonebang5.wav \
	stonebang6.wav \
	stonebang7.wav \
	stonebang8.wav \
	metalbang1.wav \
	metalbang2.wav \
	metalbang3.wav \
	metalbang4.wav \
	metalbang5.wav \
	metalbang6.wav \
	metalbang7.wav \
	metalbang8.wav \
	volcano_eruption.wav \
	synthetic_bomb.wav \
	synthetic_laser.wav \
	rocket_exhaust_1.wav \
	missile_alarm.wav \
	big_explosion.wav \
	flak_gun_sound.wav \
	missile_launch_2.wav \
	flak_hit.wav \
	bombexplosion.wav \
	synthetic_gunshot_2.wav \
	missile_explosion.wav \
	new_ground_smack.wav \
	synthetic_thunder_short.wav \
	toyota_celica_cardoor_sample.wav \
	aaaah_it_burns.wav


clean:
		/bin/rm -f *.wav
