name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install gtk2.0
    - name: make (no audio)
      run: make WITHAUDIO=no
